version: "3.8"
services:
  postgres:
    build:
      context: .
      dockerfile: ./containers/postgres/Dockerfile
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - local

networks:
  local:

volumes:
  postgresqldata:
